name: Manual Tests

on:
  workflow_dispatch:
    inputs:
      test_case:
        description: "Choose test case to run"
        required: true
        default: "full"
        type: choice
        options:
          - full
          - specific

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 22
        uses: actions/setup-java@v1
        with:
          java-version: 22

      - name: Run tests
        run: mvn clean test